# Generated by Django 5.2.18 on 2026-10-07 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_budget_budgetclassification_building_centre_place_and_more'),
        ('movements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmovement',
            name='from_building',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='assetmovement',
            name='from_division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_from', to='core.division'),
        ),
        migrations.AddField(
            model_name='assetmovement',
            name='from_inventory_type',
            field=models.CharField(blank=True, max_length=3, verbose_name='From PIR/DIR'),
        ),
        migrations.AddField(
            model_name='assetmovement',
            name='from_room',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='assetmovement',
            name='to_building',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='assetmovement',
            name='to_division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_to', to='core.division'),
        ),
        migrations.AddField(
            model_name='assetmovement',
            name='to_inventory_type',
            field=models.CharField(blank=True, max_length=3, verbose_name='To PIR/DIR'),
        ),
        migrations.AddField(
            model_name='assetmovement',
            name='to_room',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='assetmovement',
            name='movement_date',
            field=models.DateField(verbose_name='Transferred date'),
        ),
        migrations.AlterField(
            model_name='assetmovement',
            name='return_clause',
            field=models.TextField(blank=True, choices=[('Surplus', 'Surplus'), ('Obsolete', 'Obsolete'), ('Unserviceable', 'Unserviceable')]),
        ),
    ]
