# Generated by Django 5.2.18 on 2026-10-07 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatepasses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gatepass',
            options={'ordering': ['-created_at'], 'permissions': [('division_approve_gatepass', 'Can approve or reject gate passes as division admin'), ('approve_gatepass', 'Can approve gate passes in stores'), ('security_scan_gatepass', 'Can mark gate pass outward and inward')]},
        ),
        migrations.AddField(
            model_name='gatepass',
            name='division_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='division_approved_gatepasses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_gatepasses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('DIVISION_APPROVED', 'Division approved'), ('STORES_APPROVED', 'Stores approved'), ('REJECTED', 'Rejected'), ('OUTWARD', 'Marked outward'), ('INWARD', 'Marked inward'), ('CLOSED', 'Closed')], default='REQUESTED', max_length=30),
        ),
    ]
