# Generated by Django 5.2.18 on 2026-10-07 17:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('core', '0003_budget_budgetclassification_building_centre_place_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['sl_no', 'id'], 'permissions': [('scan_asset', 'Can scan asset QR pages'), ('view_sensitive_asset', 'Can view sensitive asset details')]},
        ),
        migrations.AddField(
            model_name='asset',
            name='division',
            field=models.ForeignKey(blank=True, help_text="Leave blank to use the custodian's or location's division.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='core.division'),
        ),
        migrations.AddField(
            model_name='asset',
            name='inventory_type',
            field=models.CharField(blank=True, choices=[('PIR', 'PIR'), ('DIR', 'DIR'), ('IIR', 'IIR')], max_length=3, verbose_name='Type of inventory'),
        ),
        migrations.AddField(
            model_name='asset',
            name='parent_asset',
            field=models.ForeignKey(blank=True, help_text='For accessories (monitor, keyboard, etc.), choose the main item they belong to.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accessories', to='assets.asset', verbose_name='Main item'),
        ),
        migrations.AddField(
            model_name='installation',
            name='log_book_maintained',
            field=models.BooleanField(blank=True, null=True, verbose_name='Log book maintained'),
        ),
        migrations.AddField(
            model_name='procurement',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurements', to='core.budget'),
        ),
        migrations.AddField(
            model_name='procurement',
            name='budget_classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurements', to='core.budgetclassification'),
        ),
        migrations.AddField(
            model_name='procurement',
            name='currency',
            field=models.CharField(choices=[('INR', 'Rupee (₹)'), ('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('JPY', 'Yen (¥)')], default='INR', help_text='Currency of the unit rate and bill value.', max_length=3),
        ),
        migrations.AddField(
            model_name='procurement',
            name='drr_date',
            field=models.DateField(blank=True, null=True, verbose_name='DRR date'),
        ),
        migrations.AddField(
            model_name='procurement',
            name='drr_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='DRR No.'),
        ),
        migrations.AddField(
            model_name='procurement',
            name='grin_date',
            field=models.DateField(blank=True, null=True, verbose_name='GRIN date'),
        ),
        migrations.AddField(
            model_name='procurement',
            name='grin_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='GRIN No.'),
        ),
        migrations.AddField(
            model_name='procurement',
            name='project_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurements', to='core.projectcode'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_code',
            field=models.CharField(blank=True, help_text='Optional. Can be added later when the RFID tag is fixed.', max_length=50, null=True, unique=True, verbose_name='RFID code'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='current_status',
            field=models.CharField(choices=[('IN_STOCK', 'In stock'), ('ASSIGNED', 'Issued'), ('OUTSIDE', 'Outside premises'), ('RETURN_PENDING', 'Return pending'), ('UNDER_DISPOSAL', 'Under disposal'), ('DISPOSED', 'Disposed'), ('WRITTEN_OFF', 'Written Off'), ('PASSED_OUT', 'Passed Out')], default='IN_STOCK', max_length=30),
        ),
        migrations.AlterField(
            model_name='asset',
            name='sl_no',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='SL No.'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='transaction_id',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='installation',
            name='status_of_asset',
            field=models.CharField(blank=True, choices=[('Working', 'Working'), ('Not working', 'Not working')], max_length=100),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Amount / Unit rate'),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='bill_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bill No.'),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='po_date',
            field=models.DateField(blank=True, null=True, verbose_name='PO date'),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='po_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='PO No.'),
        ),
        migrations.CreateModel(
            name='AssetVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verification_date', models.DateField(default=django.utils.timezone.localdate)),
                ('result', models.CharField(choices=[('AVAILABLE', 'Available'), ('NOT_AVAILABLE', 'Not available')], max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=250)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='assets.asset')),
                ('location', models.ForeignKey(blank=True, help_text='Where the asset was expected during verification.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications', to='core.location')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-verification_date', '-created_at'],
            },
        ),
    ]
