# Generated by Django 5.2.18 on 2026-10-07 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disposal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disposalrecord',
            options={'ordering': ['-created_at'], 'permissions': [('approve_disposalrecord', 'Can approve disposal and write-off'), ('classify_lot', 'Can classify returned items into disposal lots (Stores)')]},
        ),
    ]
